# 同義詞對應表
# 用於 ProgramRegistry 的球路名稱匹配

synonyms:
  # 基本球路
  平抽球: [平抽, 平抽擊, 平抽擊球]
  高遠球: [高遠, 後場高遠, 高遠擊球]
  吊球: [小球, 放網, 網前小球, 輕吊]
  殺球: [扣殺, 重殺, 殺球擊]
  挑球: [挑高, 挑高球]
  推球: [推擊, 推球擊]
  
  # 位置相關
  前場: [網前, 前場區]
  後場: [底線, 後場區]
  中場: [中場區, 中間]
  
  # 方向相關
  正手: [正手擊, 正手球]
  反手: [反手擊, 反手球]
  直線: [直線球, 直線擊]
  斜線: [對角, 斜線球, 對角球]
  
  # 訓練相關
  基礎訓練: [基礎, 基本訓練, 入門訓練]
  進階訓練: [進階, 高級訓練, 進階課程]
  熱身: [熱身訓練, 準備活動]
  
  # 速度相關
  快速: [高速, 快速發球]
  慢速: [低速, 慢速發球]
  中速: [中等速度, 標準速度]
  
  # 發球相關
  發球: [發球練習, 練習發球]
  多球: [多球練習, 連續發球]
  單球: [單球練習, 間隔發球]

# 反向映射（自動生成，用於快速查找）
reverse_synonyms:
  # 這裡會在程式啟動時自動生成
  # 格式：同義詞 -> 標準詞
