# 尾綴移除規則
# 用於 ProgramRegistry 的名稱正規化

# 需要移除的尾綴（按優先級排序）
suffixes:
  - "球"           # 平抽球 -> 平抽
  - "訓練"         # 基礎訓練 -> 基礎
  - "套餐"         # 訓練套餐 -> 訓練
  - "練習"         # 發球練習 -> 發球
  - "課程"         # 進階課程 -> 進階
  - "模式"         # 訓練模式 -> 訓練
  - "擊"           # 平抽擊 -> 平抽
  - "擊球"         # 平抽擊球 -> 平抽

# 特殊規則（需要完整匹配）
special_rules:
  # 某些詞彙不應該移除尾綴
  preserve:
    - "羽毛球"     # 保留完整詞彙
    - "發球機"     # 保留完整詞彙
    - "訓練球"     # 保留完整詞彙
  
  # 複合詞彙處理
  compound:
    - "正手平抽球"  # 不應該變成 "正手平抽"
    - "反手高遠球"  # 不應該變成 "反手高遠"
    - "前場吊球"    # 不應該變成 "前場吊"

# 正規化規則
normalization:
  # 全形轉半形
  fullwidth_to_halfwidth: true
  
  # 大小寫處理
  case_sensitive: false
  
  # 空白處理
  trim_whitespace: true
  normalize_spaces: true
  
  # 標點符號處理
  remove_punctuation: false  # 保留標點，避免誤判
